const options = {
  data: {
    reportData: [{
      feeFineOwner: 'Anna',
      feeFineType: 'Misc fee',
      billedAmount: '11.00',
      dateBilled: '5/13/21, 4:38 PM',
      feeFineCreatedAt: 'Circ Desk 2',
      feeFineSource: 'ADMINISTRATOR, DIKU',
      feeFineId: '409452da-7766-47d5-9e02-6ab833af0ecb',
      action: 'Payment',
      actionAmount: '11.00',
      actionDate: '5/13/21, 4:38 PM',
      actionCreatedAt: 'Circ Desk 2',
      actionSource: 'ADMINISTRATOR, DIKU',
      actionStatus: 'Paid fully',
      actionAdditionalStaffInfo: 'Staff info qqq',
      actionAdditionalPatronInfo: '',
      paymentMethod: 'cash',
      transactionInfo: '# transs',
      waiveReason: '',
      refundReason: '',
      transferAccount: '',
      patronId: '01f3931e-f9be-44fc-b808-1adb4e7f1729',
      patronName: 'Melnyk, Anna',
      patronBarcode: '777777',
      patronGroup: 'graduate',
      patronEmail: 'anna_melnyk@epam.com',
      instance: '',
      contributors: '',
      itemBarcode: '',
      callNumber: '',
      effectiveLocation: '',
      loanDate: '',
      dueDate: '7/12/21, 12:22 PM',
      returnDate: '7/12/21, 12:22 PM',
      loanPolicyId: '',
      loanPolicyName: '',
      overdueFinePolicyId: '',
      overdueFinePolicyName: '',
      lostItemPolicyId: '',
      lostItemPolicyName: '',
      loanId: '',
      holdingsRecordId: '',
      instanceId: '',
      itemId: ''
    }, {
      feeFineOwner: 'Anna',
      feeFineType: 'Misc fee',
      billedAmount: '110.00',
      dateBilled: '5/13/21, 4:38 PM',
      feeFineCreatedAt: 'Circ Desk 2',
      feeFineSource: 'ADMINISTRATOR, DIKU',
      feeFineId: 'b80e0a3d-d572-4652-8e35-19e8dcf823ef',
      action: 'Transfer',
      actionAmount: '30.00',
      actionDate: '5/13/21, 4:39 PM',
      actionCreatedAt: 'Circ Desk 2',
      actionSource: 'ADMINISTRATOR, DIKU',
      actionStatus: 'Transferred partially',
      actionAdditionalStaffInfo: 'staff infoormation',
      actionAdditionalPatronInfo: '',
      paymentMethod: '',
      waiveReason: '',
      refundReason: '',
      transferAccount: 'another-transfer-account',
      patronId: '01f3931e-f9be-44fc-b808-1adb4e7f1729',
      patronName: 'Melnyk, Anna',
      patronBarcode: '777777',
      patronGroup: 'graduate',
      patronEmail: 'anna_melnyk@epam.com',
      instance: '',
      contributors: '',
      itemBarcode: '',
      callNumber: '',
      effectiveLocation: '',
      loanDate: '',
      dueDate: '7/12/21, 12:22 PM',
      returnDate: '7/12/21, 12:22 PM',
      loanPolicyId: '',
      loanPolicyName: '',
      overdueFinePolicyId: '',
      overdueFinePolicyName: '',
      lostItemPolicyId: '',
      lostItemPolicyName: '',
      loanId: '',
      holdingsRecordId: '',
      instanceId: '',
      itemId: ''
    }, {
      feeFineOwner: 'Anna',
      feeFineType: 'Misc fee',
      billedAmount: '110.00',
      dateBilled: '5/13/21, 4:38 PM',
      feeFineCreatedAt: 'Circ Desk 2',
      feeFineSource: 'ADMINISTRATOR, DIKU',
      feeFineId: 'b80e0a3d-d572-4652-8e35-19e8dcf823ef',
      action: 'Waive',
      actionAmount: '10.00',
      actionDate: '5/13/21, 4:39 PM',
      actionCreatedAt: 'Circ Desk 2',
      actionSource: 'ADMINISTRATOR, DIKU',
      actionStatus: 'Waived partially',
      actionAdditionalStaffInfo: 'poefjqwpojf',
      actionAdditionalPatronInfo: '',
      paymentMethod: '',
      waiveReason: 'Regret',
      refundReason: '',
      transferAccount: '',
      patronId: '01f3931e-f9be-44fc-b808-1adb4e7f1729',
      patronName: 'Melnyk, Anna',
      patronBarcode: '777777',
      patronGroup: 'graduate',
      patronEmail: 'anna_melnyk@epam.com',
      instance: '',
      contributors: '',
      itemBarcode: '',
      callNumber: '',
      effectiveLocation: '',
      loanDate: '',
      dueDate: '7/12/21, 12:22 PM',
      returnDate: '7/12/21, 12:22 PM',
      loanPolicyId: '',
      loanPolicyName: '',
      overdueFinePolicyId: '',
      overdueFinePolicyName: '',
      lostItemPolicyId: '',
      lostItemPolicyName: '',
      loanId: '',
      holdingsRecordId: '',
      instanceId: '',
      itemId: ''
    }, {
      feeFineOwner: 'Anna',
      feeFineType: 'Misc fee',
      billedAmount: '110.00',
      dateBilled: '5/13/21, 4:38 PM',
      feeFineCreatedAt: 'Circ Desk 2',
      feeFineSource: 'ADMINISTRATOR, DIKU',
      feeFineId: 'b80e0a3d-d572-4652-8e35-19e8dcf823ef',
      action: 'Refund',
      actionAmount: '30.00',
      actionDate: '5/13/21, 4:39 PM',
      actionCreatedAt: 'Circ Desk 2',
      actionSource: 'ADMINISTRATOR, DIKU',
      actionStatus: 'Refunded fully',
      actionAdditionalStaffInfo: 'pkp iudg',
      actionAdditionalPatronInfo: '',
      paymentMethod: '',
      transactionInfo: 'Refunded to another-transfer-account',
      waiveReason: '',
      refundReason: 'test-refund-reason',
      transferAccount: '',
      patronId: '01f3931e-f9be-44fc-b808-1adb4e7f1729',
      patronName: 'Melnyk, Anna',
      patronBarcode: '777777',
      patronGroup: 'graduate',
      patronEmail: 'anna_melnyk@epam.com',
      instance: '',
      contributors: '',
      itemBarcode: '',
      callNumber: '',
      effectiveLocation: '',
      loanDate: '',
      dueDate: '7/12/21, 12:22 PM',
      returnDate: '7/12/21, 12:22 PM',
      loanPolicyId: '',
      loanPolicyName: '',
      overdueFinePolicyId: '',
      overdueFinePolicyName: '',
      lostItemPolicyId: '',
      lostItemPolicyName: '',
      loanId: '',
      holdingsRecordId: '',
      instanceId: '',
      itemId: ''
    }, {
      feeFineOwner: 'Anna',
      feeFineType: 'Misc fee',
      billedAmount: '110.00',
      dateBilled: '5/13/21, 4:38 PM',
      feeFineCreatedAt: 'Circ Desk 2',
      feeFineSource: 'ADMINISTRATOR, DIKU',
      feeFineId: 'b80e0a3d-d572-4652-8e35-19e8dcf823ef',
      action: 'Payment',
      actionAmount: '70.00',
      actionDate: '5/13/21, 4:40 PM',
      actionCreatedAt: 'Circ Desk 2',
      actionSource: 'ADMINISTRATOR, DIKU',
      actionStatus: 'Paid fully',
      actionAdditionalStaffInfo: 'osih 78flk lfknb',
      actionAdditionalPatronInfo: '',
      paymentMethod: 'visa',
      transactionInfo: '##657577',
      waiveReason: '',
      refundReason: '',
      transferAccount: '',
      patronId: '01f3931e-f9be-44fc-b808-1adb4e7f1729',
      patronName: 'Melnyk, Anna',
      patronBarcode: '777777',
      patronGroup: 'graduate',
      patronEmail: 'anna_melnyk@epam.com',
      instance: '',
      contributors: '',
      itemBarcode: '',
      callNumber: '',
      effectiveLocation: '',
      loanDate: '',
      dueDate: '7/12/21, 12:22 PM',
      returnDate: '7/12/21, 12:22 PM',
      loanPolicyId: '',
      loanPolicyName: '',
      overdueFinePolicyId: '',
      overdueFinePolicyName: '',
      lostItemPolicyId: '',
      lostItemPolicyName: '',
      loanId: '',
      holdingsRecordId: '',
      instanceId: '',
      itemId: ''
    }, {
      feeFineOwner: 'Anna',
      feeFineType: 'Misc fee',
      billedAmount: '19.00',
      dateBilled: '5/13/21, 4:42 PM',
      feeFineCreatedAt: 'Online',
      feeFineSource: 'ADMINISTRATOR, DIKU',
      feeFineId: '58bf9546-02e0-4761-89ac-59481fc689f3',
      action: 'Payment',
      actionAmount: '9.00',
      actionDate: '5/13/21, 4:42 PM',
      actionCreatedAt: 'Online',
      actionSource: 'ADMINISTRATOR, DIKU',
      actionStatus: 'Paid partially',
      actionAdditionalStaffInfo: 'liho uiuiu hoh',
      actionAdditionalPatronInfo: '',
      paymentMethod: 'visa',
      transactionInfo: '',
      waiveReason: '',
      refundReason: '',
      transferAccount: '',
      patronId: 'b4cee18d-f862-4ef1-95a5-879fdd619603',
      patronName: 'sheldon, bazinga',
      patronBarcode: '789',
      patronGroup: 'staff',
      patronEmail: 'sheldon@example.com',
      instance: '',
      contributors: '',
      itemBarcode: '',
      callNumber: '',
      effectiveLocation: '',
      loanDate: '',
      dueDate: '7/12/21, 12:22 PM',
      returnDate: '7/12/21, 12:22 PM',
      loanPolicyId: '',
      loanPolicyName: '',
      overdueFinePolicyId: '',
      overdueFinePolicyName: '',
      lostItemPolicyId: '',
      lostItemPolicyName: '',
      loanId: '',
      holdingsRecordId: '',
      instanceId: '',
      itemId: ''
    }, {
      feeFineOwner: 'Anna',
      feeFineType: 'Misc fee',
      billedAmount: '19.00',
      dateBilled: '5/13/21, 4:42 PM',
      feeFineCreatedAt: 'Online',
      feeFineSource: 'ADMINISTRATOR, DIKU',
      feeFineId: '58bf9546-02e0-4761-89ac-59481fc689f3',
      action: 'Payment',
      actionAmount: '10.00',
      actionDate: '5/13/21, 4:43 PM',
      actionCreatedAt: 'Online',
      actionSource: 'ADMINISTRATOR, DIKU',
      actionStatus: 'Paid fully',
      actionAdditionalStaffInfo: 'oph iuggu oihjo',
      actionAdditionalPatronInfo: '',
      paymentMethod: 'cash',
      transactionInfo: '',
      waiveReason: '',
      refundReason: '',
      transferAccount: '',
      patronId: 'b4cee18d-f862-4ef1-95a5-879fdd619603',
      patronName: 'sheldon, bazinga',
      patronBarcode: '789',
      patronGroup: 'staff',
      patronEmail: 'sheldon@example.com',
      instance: '',
      contributors: '',
      itemBarcode: '',
      callNumber: '',
      effectiveLocation: '',
      loanDate: '',
      dueDate: '7/12/21, 12:22 PM',
      returnDate: '7/12/21, 12:22 PM',
      loanPolicyId: '',
      loanPolicyName: '',
      overdueFinePolicyId: '',
      overdueFinePolicyName: '',
      lostItemPolicyId: '',
      lostItemPolicyName: '',
      loanId: '',
      holdingsRecordId: '',
      instanceId: '',
      itemId: ''
    }, {
      feeFineOwner: 'Anna',
      feeFineType: 'Misc fee',
      billedAmount: '111.00',
      dateBilled: '7/9/21, 3:39 PM',
      feeFineCreatedAt: 'Online',
      feeFineSource: 'ADMINISTRATOR, DIKU',
      feeFineId: 'dfa1f31a-f3b4-4afa-a40c-3b2114fc4746',
      action: 'Payment',
      actionAmount: '12.00',
      actionDate: '7/9/21, 3:39 PM',
      actionCreatedAt: 'Online',
      actionSource: 'ADMINISTRATOR, DIKU',
      actionStatus: 'Paid partially',
      actionAdditionalStaffInfo: 'ddcvzvffd',
      actionAdditionalPatronInfo: '',
      paymentMethod: 'cash',
      transactionInfo: '1111',
      waiveReason: '',
      refundReason: '',
      transferAccount: '',
      patronId: '27bc1f87-8c08-437a-be09-1df885262497',
      patronName: 'Kurash, Alexander',
      patronBarcode: '10001',
      patronGroup: 'staff',
      patronEmail: 'Oleksandr_Kurash@epam.com',
      instance: 'A semantic web primer',
      contributors: 'Antoniou, Grigoris, Van Harmelen, Frank',
      itemBarcode: '90000',
      callNumber: 'TK5105.88815 . A58 2004 FT MEADE',
      effectiveLocation: 'Main Library',
      loanDate: '',
      dueDate: '7/12/21, 12:22 PM',
      returnDate: '7/12/21, 12:22 PM',
      loanPolicyId: '',
      loanPolicyName: '',
      overdueFinePolicyId: '',
      overdueFinePolicyName: '',
      lostItemPolicyId: '',
      lostItemPolicyName: '',
      loanId: '',
      holdingsRecordId: 'e3ff6133-b9a2-4d4c-a1c9-dc1867d4df19',
      instanceId: '5bf370e0-8cca-4d9c-82e4-5170ab2a0a39',
      itemId: '100d10bf-2f06-4aa0-be15-0b95b2d9f9e3'
    }],
    reportStats: {
      byFeeFineOwner: [{
        name: 'Anna',
        totalAmount: '182.00',
        totalCount: '8'
      }, {
        name: 'Fee/fine owner totals',
        totalAmount: '182.00',
        totalCount: '8'
      }],
      byFeeFineType: [{
        name: 'Misc fee',
        totalAmount: '182.00',
        totalCount: '8'
      }, {
        name: 'Fee/fine type totals',
        totalAmount: '182.00',
        totalCount: '8'
      }],
      byAction: [{
        name: 'Payment',
        totalAmount: '112.00',
        totalCount: '5'
      }, {
        name: 'Transfer',
        totalAmount: '30.00',
        totalCount: '1'
      }, {
        name: 'Waive',
        totalAmount: '10.00',
        totalCount: '1'
      }, {
        name: 'Refund',
        totalAmount: '30.00',
        totalCount: '1'
      }, {
        name: 'Action totals',
        totalAmount: '182.00',
        totalCount: '8'
      }],
      byPaymentMethod: [{
        name: 'cash',
        totalAmount: '33.00',
        totalCount: '3'
      }, {
        name: 'another-transfer-account',
        totalAmount: '30.00',
        totalCount: '1'
      }, {
        name: 'Regret',
        totalAmount: '10.00',
        totalCount: '1'
      }, {
        name: 'test-refund-reason',
        totalAmount: '30.00',
        totalCount: '1'
      }, {
        name: 'visa',
        totalAmount: '79.00',
        totalCount: '2'
      }, {
        name: 'Payment method totals',
        totalAmount: '182.00',
        totalCount: '8'
      }],
      byWaiveReason: [{
        name: 'Regret',
        totalAmount: '10.00',
        totalCount: '1'
      }, {
        name: 'Waive reason totals',
        totalAmount: '10.00',
        totalCount: '1'
      }],
      byRefundReason: [{
        name: 'test-refund-reason',
        totalAmount: '30.00',
        totalCount: '1'
      }, {
        name: 'Refund reason totals',
        totalAmount: '30.00',
        totalCount: '1'
      }],
      byTransferAccount: [{
        name: 'another-transfer-account',
        totalAmount: '30.00',
        totalCount: '1'
      }, {
        name: 'Transfer account totals',
        totalAmount: '30.00',
        totalCount: '1'
      }]
    }
  },
  intl: {
    formatMessage: jest.fn(() => ''),
    formatTime: jest.fn(),
    formatDate: jest.fn()
  },
  headerData: {
    createdAt: 'Online',
    feeFineOwner: 'Anna',
    startDate: '2020/01/05',
    endDate: '2021/01/05'
  }
};

export default options;
