import './stripesConfig.mock';
import './stripesCore.mock';
import './stripes.mock';
import './intl.mock';
import './stripesIcon.mock';
import './stripesComponents.mock';
import './stripesSmartComponent.mock';
import './stripesUtils.mock';
import './currencyData.mock';
