# This workflow will do a clean install of node dependencies, build the source code 
# and run tests across different versions of node.  
# For more information see: 
# https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

# FOLIO configurable env:
#   - YARN_TEST_OPTIONS
#   - SONAR_SRC_DIR


name: buildNPM CI

on: 
  push:
    paths-ignore:
      - 'translations/**'
  pull_request:
     paths-ignore:
      - 'translations/**'

jobs:
  build:
    env:
      YARN_TEST_OPTIONS: '--bundle --karma.singleRun --karma.browsers ChromeDocker --karma.reporters mocha junit --coverage'
      SONAR_SRC_DIR: './src'
      FOLIO_NPM_REGISTRY:  https://repository.folio.org/repository/npm-folioci/


    runs-on: ubuntu-latest
    steps:
      - uses: folio-org/checkout@v2
      - run: yarn config set @folio:registry $FOLIO_NPM_REGISTRY
      - run: git clone https://github.com/folio-org/folio-tools.git
      - name: Set FOLIO NPM snapshot version
        run: npm --no-git-tag-version version `folio-tools/github-actions-scripts/folioci_npmver.sh`
        env: 
          JOB_ID: ${{ env.GITHUB_RUN_NUMBER }}
      - run: echo $JOB_ID
      - name: Yarn install
        id: install
        run: yarn install
      - name: Yarn list
        id: list
        run: yarn list --pattern @folio
      - name: Yarn lint
        id: lint
        run: yarn lint
        continue-on-error: true
      - run: rm -rf folio-tools
          
      
