# This workflow will publish the Jest unit test results and retain them for a period of 30 days. This also gives permission
# to forked repositories and dependabots to do write operations which are configured in this workflow.

name: Publish Jest Results

on:
  workflow_run:
    workflows: ["buildNPM Snapshot"]
    types:
      - completed

jobs:
  publish-jest-results-snapshot:
    env:
      JEST_JUNIT_OUTPUT_DIR: "artifacts/jest-junit"
      ARTIFACT_NAME: "Jest Unit Test Result"

    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'

    steps:
      - name: Download test results file
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: buildNPM Snapshot
          run_id: ${{ github.event.workflow_run.id }}
          name: Jest Unit Test Results

      - name: Read test results file
        id: jestResultFile
        uses: juliangruber/read-file-action@v1
        with:
          path: ./jest-unit-test-results.zip

      - name: Unzip test results file
        run: unzip ./${{ env.ARTIFACT_NAME }}.zip
        

      - name: Publish Jest unit test results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          commit: ${{ github.event.workflow_run.head_sha }}
          event_name: ${{ github.event.workflow_run.event }}
          files: "${{ env.JEST_JUNIT_OUTPUT_DIR }}/*.xml"
          check_name: Jest Unit Test Results
          comment_mode: update last
          comment_title: Jest Unit Test Results
